/**
 * Discovery Report Generator
 *
 * Produces human-readable markdown reports from discovery and download results.
 */

import type { CandidateEntry } from './candidate.schema';
import type { SourceRegistryEntry } from './source-registry.schema';

// ============================================================================
// Discovery Report
// ============================================================================

export function generateDiscoveryReport(
  country: string,
  sourcesScanned: SourceRegistryEntry[],
  candidates: CandidateEntry[],
  errors: string[],
  dryRun: boolean,
): string {
  const now = new Date().toISOString();
  const lines: string[] = [];

  lines.push(`# Discovery Report — ${country}`);
  lines.push('');
  lines.push(`Generated: ${now}`);
  lines.push(`Mode: ${dryRun ? 'DRY RUN (no network requests)' : 'LIVE'}`);
  lines.push('');

  // Sources summary
  lines.push('## Sources Scanned');
  lines.push('');
  lines.push('| Regulator | URL | Mode | Priority |');
  lines.push('| --- | --- | --- | --- |');
  for (const src of sourcesScanned) {
    lines.push(`| ${src.regulator} | ${src.baseUrl} | ${src.crawlMode} | ${src.priority} |`);
  }
  lines.push('');

  // Candidates summary
  lines.push('## Candidates Found');
  lines.push('');
  lines.push(`Total: ${candidates.length}`);
  lines.push('');

  if (candidates.length > 0) {
    const byCat = countBy(candidates, (c) => c.suggestedCategory);
    const byType = countBy(candidates, (c) => c.suggestedDocumentType);
    const byDecision = countBy(candidates, (c) => c.decision);

    lines.push('### By Category');
    lines.push('');
    for (const [key, count] of Object.entries(byCat).sort((a, b) => b[1] - a[1])) {
      lines.push(`- ${key}: ${count}`);
    }
    lines.push('');

    lines.push('### By Document Type');
    lines.push('');
    for (const [key, count] of Object.entries(byType).sort((a, b) => b[1] - a[1])) {
      lines.push(`- ${key}: ${count}`);
    }
    lines.push('');

    lines.push('### By Decision');
    lines.push('');
    for (const [key, count] of Object.entries(byDecision).sort((a, b) => b[1] - a[1])) {
      lines.push(`- ${key}: ${count}`);
    }
    lines.push('');

    lines.push('### Candidate List');
    lines.push('');
    lines.push('| ID | Title | Category | Type | Decision |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const c of candidates) {
      lines.push(`| ${c.id} | ${c.normalizedTitle} | ${c.suggestedCategory} | ${c.suggestedDocumentType} | ${c.decision} |`);
    }
    lines.push('');
  }

  // Errors
  if (errors.length > 0) {
    lines.push('## Errors');
    lines.push('');
    for (const err of errors) {
      lines.push(`- ❌ ${err}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('> This report was auto-generated by `pnpm corpus:discover`. Candidates must be manually reviewed before approval.');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Download Report
// ============================================================================

export function generateDownloadReport(
  country: string,
  downloaded: CandidateEntry[],
  skipped: CandidateEntry[],
  failed: Array<{ entry: CandidateEntry; error: string }>,
  dryRun: boolean,
): string {
  const now = new Date().toISOString();
  const lines: string[] = [];

  lines.push(`# Download Report — ${country}`);
  lines.push('');
  lines.push(`Generated: ${now}`);
  lines.push(`Mode: ${dryRun ? 'DRY RUN (no downloads)' : 'LIVE'}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`- Downloaded: ${downloaded.length}`);
  lines.push(`- Skipped (not APPROVED): ${skipped.length}`);
  lines.push(`- Failed: ${failed.length}`);
  lines.push('');

  if (downloaded.length > 0) {
    lines.push('## Downloaded');
    lines.push('');
    lines.push('| Title | Local Path | Checksum |');
    lines.push('| --- | --- | --- |');
    for (const d of downloaded) {
      lines.push(`| ${d.normalizedTitle} | ${d.downloadedLocalPath ?? 'N/A'} | ${d.checksumSha256 ? d.checksumSha256.slice(0, 16) + '...' : 'N/A'} |`);
    }
    lines.push('');
  }

  if (failed.length > 0) {
    lines.push('## Failed');
    lines.push('');
    for (const f of failed) {
      lines.push(`- ❌ **${f.entry.normalizedTitle}**: ${f.error}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('> This report was auto-generated by `pnpm corpus:download`.');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Helpers
// ============================================================================

function countBy<T>(items: T[], keyFn: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const key = keyFn(item);
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}
