-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BILLING_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SECURITY_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

-- Migrate existing ADMIN rows to SUPER_ADMIN
UPDATE "User" SET "role" = 'SUPER_ADMIN' WHERE "role" = 'ADMIN';
