import { TRPCError } from '@trpc/server';
import { createHash } from 'crypto';
import { z } from 'zod';
import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  Packer,
  PageNumber,
  Paragraph,
  TextRun,
} from 'docx';
import { router, orgMemberProcedure } from '../trpc/trpc';
import { BillingMetric } from '@prisma/client';
import { rateLimited, withPlanContext, requirePlanFeature, resolveUsageLimit } from '../trpc/middleware';
import {
  generatePolicySchema,
  listPoliciesSchema,
  getPolicySchema,
  updatePolicySchema,
  deletePolicySchema,
  exportPolicySchema,
  refinePolicySchema,
  verifyCitationsSchema,
} from '../schemas/policy.schema';
import { policyCache } from '@/lib/redis/cache.service';
import { logger } from '@/utils/logger';
import { aiJobRunner } from '@/modules/ai-jobs/ai-job-runner';
import { regulatoryIntelligenceService } from '@/modules/regulatory-intelligence/regulatory-intelligence.service';
import {
  JurisdictionContractError,
  serializeJurisdictionContext,
  type JurisdictionContext,
} from '@/types/jurisdiction';
import {
  JurisdictionAuthorizationError,
  resolveJurisdictionEntitlement,
  toTrpcJurisdictionAuthorizationError,
} from '@/modules/jurisdiction/jurisdiction-entitlements';

const POLICY_EXPORT_TTL_SECONDS = 60 * 60;

function sanitizeExportName(name: string | null | undefined): string {
  const base = (name ?? 'Policy').trim() || 'Policy';
  return base
    .replace(/[^a-zA-Z0-9._ -]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 80);
}

function policyContent(policy: any): string {
  const parts = [
    policy.executiveSummary ? `## Executive Summary\n\n${policy.executiveSummary}` : null,
    policy.analysis ? `## Regulatory Analysis\n\n${policy.analysis}` : null,
    policy.content,
  ].filter(Boolean);
  return parts.join('\n\n').trim();
}

function formatPolicyMarkdown(policy: any): string {
  const lines = [
    `# ${policy.title ?? 'Policy'}`,
    '',
    `Generated: ${policy.createdAt.toISOString().slice(0, 10)}`,
    `Version: ${policy.version ?? 1}`,
    `Status: ${policy.status}`,
    policy.organizationType ? `Organization Type: ${policy.organizationType}` : null,
    Array.isArray(policy.regulatoryAreas) && policy.regulatoryAreas.length > 0
      ? `Regulatory Areas: ${policy.regulatoryAreas.join(', ')}`
      : null,
    '',
    policy.scenario ? `## Scenario\n\n${policy.scenario}` : null,
    policyContent(policy),
  ].filter((line): line is string => line !== null);

  if (policy.citations?.length) {
    lines.push('', '## Legal Citations');
    policy.citations.forEach((citation: any, index: number) => {
      const source = citation.actName ?? citation.document?.actName ?? 'Legal source';
      const section = citation.section ? `, Section ${citation.section}` : '';
      lines.push(`${index + 1}. ${source}${section}`);
      if (citation.textSnippet) lines.push(`   ${citation.textSnippet}`);
    });
  }

  lines.push('', '---', 'Generated by SheriaBot. Verify against official sources before filing.');
  return lines.join('\n');
}

function rawCitationRecord(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function markdownToDocxParagraphs(markdown: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  let buffer: string[] = [];

  const flush = () => {
    const text = buffer.join(' ').trim();
    if (text) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({ text, font: 'Arial', size: 22, color: '334155' })],
        spacing: { after: 140 },
      }));
    }
    buffer = [];
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      flush();
      continue;
    }

    const heading = /^(#{1,3})\s+(.+)$/.exec(line);
    if (heading) {
      flush();
      paragraphs.push(new Paragraph({
        text: heading[2].replace(/[*_`]/g, ''),
        heading: heading[1].length === 1 ? HeadingLevel.HEADING_1 : HeadingLevel.HEADING_2,
        spacing: { before: 160, after: 100 },
      }));
      continue;
    }

    const listItem = /^[-*+]\s+(.+)$/.exec(line) ?? /^\d+\.\s+(.+)$/.exec(line);
    if (listItem) {
      flush();
      paragraphs.push(new Paragraph({
        bullet: { level: 0 },
        children: [new TextRun({ text: listItem[1].replace(/[*_`]/g, ''), font: 'Arial', size: 22, color: '334155' })],
        spacing: { after: 80 },
      }));
      continue;
    }

    buffer.push(line.replace(/[*_`]/g, ''));
  }

  flush();
  return paragraphs;
}

async function buildPolicyDocx(policy: any): Promise<Buffer> {
  const doc = new Document({
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: 'SheriaBot', bold: true, font: 'Arial', size: 18, color: '1A2B4A' }),
                new TextRun({ text: ' | Policy Export', font: 'Arial', size: 18, color: '475569' }),
              ],
              border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: '1A2B4A' } },
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: 'Confidential | Page ', size: 16, color: '64748B' }),
                new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '64748B' }),
              ],
            }),
          ],
        }),
      },
      children: markdownToDocxParagraphs(formatPolicyMarkdown(policy)),
    }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

function pdfEscape(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrapPdfLines(text: string, width = 92): string[] {
  return text
    .replace(/\r\n/g, '\n')
    .split('\n')
    .flatMap((line) => {
      if (!line.trim()) return [''];
      const words = line.split(/\s+/);
      const wrapped: string[] = [];
      let current = '';
      for (const word of words) {
        const next = current ? `${current} ${word}` : word;
        if (next.length > width) {
          if (current) wrapped.push(current);
          current = word;
        } else {
          current = next;
        }
      }
      if (current) wrapped.push(current);
      return wrapped;
    });
}

function buildSimplePdf(text: string): Buffer {
  const lines = wrapPdfLines(text, 86);
  const linesPerPage = 46;
  const pages = lines.length > 0
    ? Array.from({ length: Math.ceil(lines.length / linesPerPage) }, (_, index) =>
      lines.slice(index * linesPerPage, (index + 1) * linesPerPage),
    )
    : [['']];

  const fontObjectId = 3;
  const firstPageObjectId = 4;
  const firstContentObjectId = firstPageObjectId + pages.length;
  const pageObjectIds = pages.map((_, index) => firstPageObjectId + index);
  const contentObjectIds = pages.map((_, index) => firstContentObjectId + index);

  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    `2 0 obj << /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pages.length} >> endobj`,
    `${fontObjectId} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj`,
  ];

  pages.forEach((_, index) => {
    objects.push(
      `${pageObjectIds[index]} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectIds[index]} 0 R >> endobj`,
    );
  });

  pages.forEach((pageLines, index) => {
    const commands = [
      'BT',
      '/F1 13 Tf',
      `50 760 Td (${pdfEscape('SheriaBot Policy Export')}) Tj`,
      '/F1 9 Tf',
      `0 -18 Td (${pdfEscape(`Page ${index + 1} of ${pages.length}`)}) Tj`,
      'ET',
      'BT',
      '/F1 10 Tf',
      '50 710 Td',
    ];

    pageLines.forEach((line, lineIndex) => {
      if (lineIndex > 0) commands.push('0 -14 Td');
      commands.push(`(${pdfEscape(line)}) Tj`);
    });

    commands.push(
      'ET',
      'BT',
      '/F1 8 Tf',
      `50 34 Td (${pdfEscape('Confidential. Verify against official sources before filing.')}) Tj`,
      'ET',
    );

    const stream = commands.join('\n');
    objects.push(`${contentObjectIds[index]} 0 obj << /Length ${Buffer.byteLength(stream, 'utf8')} >> stream\n${stream}\nendstream endobj`);
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${object}\n`;
  }
  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'utf8');
}

async function buildPolicyExportBuffer(policy: any, format: 'PDF' | 'DOCX' | 'MD'): Promise<Buffer> {
  const markdown = formatPolicyMarkdown(policy);
  if (format === 'DOCX') return buildPolicyDocx(policy);
  if (format === 'PDF') return buildSimplePdf(markdown);
  return Buffer.from(markdown, 'utf8');
}

/**
 * Policy Router
 *
 * Handles policy CRUD operations and AI-powered policy generation.
 * Includes export, refinement, and citation verification features.
 */
export const policyRouter = router({
  /**
   * List policies with pagination and filters
   *
   * @protected
   */
  list: orgMemberProcedure
    .input(listPoliciesSchema)
    .query(async ({ input, ctx }) => {
      try {
        const { page, limit, status, regulatoryArea: _regulatoryArea, search } = input;
        const skip = (page - 1) * limit;

        // Note: deletedAt filter is also applied by Prisma soft-delete middleware.
        // Keeping explicit filter as defense-in-depth.
        const where: import('@prisma/client').Prisma.PolicyWhereInput = {
          deletedAt: null,
        };

        if (ctx.user!.role === 'ADMIN') {
          // Admin sees all policies globally  -  audit log required
          logger.info({
            type: 'admin_policy_list_accessed',
            adminUserId: ctx.user!.id,
          });
        } else {
          // Org-scoped: show all policies belonging to the user's organization
          where.organizationId = ctx.orgMembership!.organizationId;
        }

        if (status) {
          where.status = status;
        }

        if (search) {
          where.OR = [
            { title: { contains: search, mode: 'insensitive' } },
            { scenario: { contains: search, mode: 'insensitive' } },
          ];
        }

        const [policies, total] = await Promise.all([
          ctx.prisma.policy.findMany({
            where,
            skip,
            take: limit,
            orderBy: { createdAt: 'desc' },
            select: {
              id: true,
              title: true,
              scenario: true,
              status: true,
              regulatoryAreas: true,
              createdAt: true,
              updatedAt: true,
              user: {
                select: {
                  id: true,
                  fullName: true,
                  email: true,
                },
              },
            },
          }),
          ctx.prisma.policy.count({ where }),
        ]);

        return {
          policies,
          pagination: {
            page,
            limit,
            total,
            pages: Math.ceil(total / limit),
          },
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_list_error',
          userId: ctx.user!.id,
          error: error.message,
        });

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to list policies',
          cause: error,
        });
      }
    }),

  /**
   * Get policy by ID with citations
   *
   * @protected
   */
  get: orgMemberProcedure
    .input(getPolicySchema)
    .query(async ({ input, ctx }) => {
      try {
        // Try cache first
        const cached = await policyCache.get(input.id);
        if (cached) {
          return cached;
        }

        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.id },
          include: {
            user: {
              select: {
                id: true,
                fullName: true,
                email: true,
              },
            },
            citations: {
              orderBy: { createdAt: 'asc' },
            },
          },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Check access  -  org-scoped with userId fallback for legacy policies
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        // Cache
        await policyCache.set(input.id, policy);

        return policy;
      } catch (error: any) {
        logger.error({
          type: 'policy_get_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to get policy',
          cause: error,
        });
      }
    }),

  /**
   * Generate policy with AI
   *
   * @protected
   * @rate-limited
   */
  generate: orgMemberProcedure
    .use(rateLimited('policyGeneration'))
    .use(withPlanContext)
    .use(requirePlanFeature('policyGeneration'))
    .input(generatePolicySchema)
    .mutation(async ({ input, ctx }) => {
      const startTime = Date.now();

      try {
        let jurisdictionContext: JurisdictionContext;
        try {
          const entitlement = await resolveJurisdictionEntitlement({
            prisma: ctx.prisma as any,
            organizationId: ctx.orgMembership!.organizationId,
            effectivePlan: ctx.plan ?? 'REGULATOR',
            requestedJurisdictions: undefined,
            source: 'ORGANIZATION_HOME',
            audit: {
              userId: ctx.user!.id,
              route: 'trpc.policy.generate',
            },
          });
          jurisdictionContext = entitlement.jurisdictionContext;
        } catch (error) {
          if (error instanceof JurisdictionContractError) {
            throw new TRPCError({ code: 'BAD_REQUEST', message: error.message, cause: error });
          }
          if (error instanceof JurisdictionAuthorizationError) throw toTrpcJurisdictionAuthorizationError(error);
          throw error;
        }

        if (ctx.user?.id) {
          const { section34RestrictionService } = await import('@/modules/user/restriction.service');
          const check = await section34RestrictionService.isProcessingPermitted(ctx.user.id, 'POLICY_GENERATION');
          if (!check.permitted) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: check.reason ?? 'Policy generation restricted pursuant to DPA Section 34',
            });
          }
        }
        const usagePatch = await resolveUsageLimit(ctx, BillingMetric.POLICY_GENERATIONS, { deferIncrement: true });

        logger.info({
          type: 'policy_generation_start',
          userId: ctx.user!.id,
          organizationType: input.organizationType,
          regulatoryAreas: input.regulatoryAreas,
        });

        // Create policy record  -  cast to any since schema differs
        const policy = await (ctx.prisma.policy.create as any)({
          data: {
            title: input.title || `Policy for ${input.organizationType}`,
            scenario: input.scenario,
            organizationType: input.organizationType,
            regulatoryAreas: input.regulatoryAreas,
            specificRequirements: input.specificRequirements,
            targetAudience: input.targetAudience,
            status: 'GENERATING',
            userId: ctx.user!.id,
            organizationId: ctx.orgMembership!.organizationId,
            urgency: 'medium',
            stakeholders: [],
          },
        });

        // Commit usage counter now that the DB record exists.
        // Consumed at queue time (not AI completion) to prevent free retries on AI failure.
        await usagePatch.incrementUsage?.();

        const idempotencyKey = createHash('sha256')
          .update(['policy-generation', policy.id, ctx.user!.id].join(':'))
          .digest('hex');

        const job = await aiJobRunner.enqueue({
          type: 'POLICY_GENERATION',
          idempotencyKey,
          targetEntityType: 'Policy',
          targetEntityId: policy.id,
          userId: ctx.user!.id,
          organizationId: ctx.orgMembership!.organizationId,
          payload: {
            scenario: input.scenario,
            organizationType: input.organizationType,
            regulatoryAreas: input.regulatoryAreas,
            specificRequirements: input.specificRequirements,
            targetAudience: input.targetAudience,
            ...serializeJurisdictionContext(jurisdictionContext),
            requestedByEmail: ctx.user!.email,
            queuedAt: new Date(startTime).toISOString(),
          },
          maxAttempts: 3,
          priority: 5,
        });

        // Return immediately with policy ID
        return {
          policyId: policy.id,
          jobId: job.id,
          status: 'GENERATING',
          message: 'Policy generation started. You will be notified when complete.',
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_generation_error',
          userId: ctx.user!.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to start policy generation',
          cause: error,
        });
      }
    }),

  /**
   * Update policy
   *
   * @protected
   */
  update: orgMemberProcedure
    .input(updatePolicySchema)
    .mutation(async ({ input, ctx }) => {
      try {
        const { id, ...data } = input;

        // Check access
        const existingPolicy = await ctx.prisma.policy.findUnique({
          where: { id },
        });

        if (!existingPolicy || existingPolicy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = existingPolicy.organizationId
            ? existingPolicy.organizationId === ctx.orgMembership!.organizationId
            : existingPolicy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        const policy = await (ctx.prisma.policy.update as any)({
          where: { id },
          data: {
            ...data,
            updatedAt: new Date(),
          },
        });

        // Clear cache
        await policyCache.delete(id);

        logger.info({
          type: 'policy_updated',
          userId: ctx.user!.id,
          policyId: id,
          fields: Object.keys(data),
        });

        return policy;
      } catch (error: any) {
        logger.error({
          type: 'policy_update_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to update policy',
          cause: error,
        });
      }
    }),

  /**
   * Delete policy (soft delete)
   *
   * @protected
   */
  delete: orgMemberProcedure
    .input(deletePolicySchema)
    .mutation(async ({ input, ctx }) => {
      try {
        // Check access
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.id },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        await ctx.prisma.policy.update({
          where: { id: input.id },
          data: { deletedAt: new Date() },
        });

        // Clear cache
        await policyCache.delete(input.id);

        logger.info({
          type: 'policy_deleted',
          userId: ctx.user!.id,
          policyId: input.id,
        });

        return {
          success: true,
          message: 'Policy deleted successfully',
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_delete_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to delete policy',
          cause: error,
        });
      }
    }),

  /**
   * Export policy to PDF/DOCX
   *
   * @protected
   */
  export: orgMemberProcedure
    .input(exportPolicySchema)
    .mutation(async ({ input, ctx }) => {
      try {
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.id },
          include: {
            citations: { include: { document: { select: { actName: true } } } },
            user: { select: { fullName: true, email: true } },
            organization: { select: { name: true } },
          },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Check access
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        if (!policy.content?.trim() && !policy.executiveSummary?.trim() && !policy.analysis?.trim()) {
          throw new TRPCError({
            code: 'BAD_REQUEST',
            message: 'This policy has no generated content to export.',
          });
        }

        const exportBuffer = await buildPolicyExportBuffer(policy, input.format);
        const timestamp = Date.now();
        const extension = input.format === 'MD' ? 'md' : input.format.toLowerCase();
        const filename = `SheriaBot_Policy_${sanitizeExportName(policy.title)}_${timestamp}.${extension}`;

        const uploadResult = await ctx.storageService.uploadPolicyExport(
          exportBuffer,
          filename,
          policy.id,
          ctx.user!.id,
        );
        const downloadUrl = await ctx.storageService.getDownloadUrl(
          uploadResult.key,
          POLICY_EXPORT_TTL_SECONDS,
          false,
          filename,
        );

        ctx.prisma.auditLog.create({
          data: {
            userId: ctx.user!.id,
            action: 'POLICY_EXPORT',
            entityType: 'Policy',
            entityId: policy.id,
            metadata: {
              format: input.format,
              filename,
              r2Key: uploadResult.key,
              fileSize: exportBuffer.length,
            },
            ipAddress: ctx.req.ip ?? null,
            userAgent: (ctx.req.headers['user-agent'] as string | undefined) ?? null,
          },
        }).catch((err: unknown) => {
          logger.error({
            type: 'policy_export_audit_log_failed',
            userId: ctx.user!.id,
            policyId: policy.id,
            error: err instanceof Error ? err.message : String(err),
          });
        });

        logger.info({
          type: 'policy_exported',
          userId: ctx.user!.id,
          policyId: input.id,
          format: input.format,
          filename,
          fileSize: exportBuffer.length,
        });

        return {
          downloadUrl,
          filename,
          fileSize: exportBuffer.length,
          expiresAt: new Date(Date.now() + POLICY_EXPORT_TTL_SECONDS * 1000).toISOString(),
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_export_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to export policy',
          cause: error,
        });
      }
    }),

  /**
   * Refine policy with AI
   *
   * @protected
   * @rate-limited
   */
  refine: orgMemberProcedure
    .use(rateLimited('policyRefinement'))
    .input(refinePolicySchema)
    .mutation(async ({ input, ctx }) => {
      try {
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.id },
          include: { citations: true },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Check access
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        const currentContent = policyContent(policy);
        if (!currentContent) {
          throw new TRPCError({
            code: 'BAD_REQUEST',
            message: 'This policy has no generated content to refine.',
          });
        }

        const result = await ctx.aiService.refinePolicy(
          currentContent,
          input.refinementInstructions,
        );

        const refinedPolicy = await (ctx.prisma.$transaction as any)(async (tx: any) => {
          await tx.policy.updateMany({
            where: {
              OR: [
                { id: policy.parentId ?? policy.id },
                { parentId: policy.parentId ?? policy.id },
              ],
            },
            data: { isLatestVersion: false },
          });

          const nextVersion = (policy.version ?? 1) + 1;
          const rootId = policy.parentId ?? policy.id;

          const created = await tx.policy.create({
            data: {
              userId: policy.userId,
              organizationId: policy.organizationId,
              title: policy.title,
              scenario: policy.scenario,
              regulatoryAreas: policy.regulatoryAreas,
              urgency: policy.urgency,
              stakeholders: policy.stakeholders,
              organizationType: policy.organizationType,
              specificRequirements: policy.specificRequirements,
              targetAudience: policy.targetAudience,
              executiveSummary: result.sections.executiveSummary || policy.executiveSummary,
              analysis: result.sections.regulatoryLandscape || policy.analysis,
              content: result.content,
              status: 'COMPLETED',
              parentId: rootId,
              version: nextVersion,
              isLatestVersion: true,
              generationMetadata: {
                ...(typeof policy.generationMetadata === 'object' && policy.generationMetadata !== null
                  ? policy.generationMetadata
                  : {}),
                refinedFromPolicyId: policy.id,
                refinementInstructions: input.refinementInstructions,
                aiModel: result.model,
                tokensUsed: result.inputTokens + result.outputTokens,
                refinedAt: new Date().toISOString(),
              },
            },
          });

          if (policy.citations.length > 0) {
            await tx.citation.createMany({
              data: policy.citations.map((citation: any) => ({
                policyId: created.id,
                actName: citation.actName,
                section: citation.section,
                subsection: citation.subsection,
                textSnippet: citation.textSnippet,
                confidence: citation.confidence,
                verified: citation.verified,
                documentId: citation.documentId,
                rawSource: citation.rawSource,
              })),
            });
          }

          return created;
        });

        await Promise.all([
          policyCache.delete(policy.id),
          policyCache.delete(refinedPolicy.id),
        ]);

        ctx.prisma.auditLog.create({
          data: {
            userId: ctx.user!.id,
            action: 'POLICY_UPDATE',
            entityType: 'Policy',
            entityId: refinedPolicy.id,
            metadata: {
              refinedFromPolicyId: policy.id,
              version: refinedPolicy.version,
              tokensUsed: result.inputTokens + result.outputTokens,
            },
            ipAddress: ctx.req.ip ?? null,
            userAgent: (ctx.req.headers['user-agent'] as string | undefined) ?? null,
          },
        }).catch((err: unknown) => {
          logger.error({
            type: 'policy_refine_audit_log_failed',
            userId: ctx.user!.id,
            policyId: policy.id,
            error: err instanceof Error ? err.message : String(err),
          });
        });

        logger.info({
          type: 'policy_refined',
          userId: ctx.user!.id,
          policyId: input.id,
          refinedPolicyId: refinedPolicy.id,
          version: refinedPolicy.version,
        });

        return {
          success: true,
          policyId: refinedPolicy.id,
          version: refinedPolicy.version,
          message: 'Policy refined successfully',
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_refine_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to refine policy',
          cause: error,
        });
      }
    }),

  /**
   * Verify policy citations with AI
   *
   * @protected
   */
  verifyCitations: orgMemberProcedure
    .use(withPlanContext)
    .input(verifyCitationsSchema)
    .query(async ({ input, ctx }) => {
      try {
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.id },
          include: { citations: true },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Check access
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;

          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        let jurisdictionContext: JurisdictionContext;
        try {
          const entitlement = await resolveJurisdictionEntitlement({
            prisma: ctx.prisma as any,
            organizationId: ctx.orgMembership!.organizationId,
            effectivePlan: ctx.plan ?? 'REGULATOR',
            requestedJurisdictions: undefined,
            source: 'ORGANIZATION_HOME',
            audit: {
              userId: ctx.user!.id,
              route: 'trpc.policy.verifyCitations',
            },
          });
          jurisdictionContext = entitlement.jurisdictionContext;
        } catch (error) {
          if (error instanceof JurisdictionContractError) {
            throw new TRPCError({ code: 'BAD_REQUEST', message: error.message, cause: error });
          }
          if (error instanceof JurisdictionAuthorizationError) throw toTrpcJurisdictionAuthorizationError(error);
          throw error;
        }

        const citationTargets = policy.citations
          .map((citation) => {
            const rawSource = rawCitationRecord(citation.rawSource);
            const text = typeof citation.textSnippet === 'string' && citation.textSnippet.trim().length > 0
              ? citation.textSnippet
              : typeof rawSource.textSnippet === 'string'
                ? rawSource.textSnippet
                : undefined;
            if (!text) return null;
            return {
              citation,
              text,
              vectorId: typeof rawSource.vectorId === 'string' ? rawSource.vectorId : undefined,
              chunkId: typeof rawSource.chunkId === 'string' ? rawSource.chunkId : undefined,
              documentId: citation.documentId ?? (typeof rawSource.documentId === 'string' ? rawSource.documentId : undefined),
            };
          })
          .filter((target): target is NonNullable<typeof target> => target !== null);

        const checks = await Promise.all(
          citationTargets.map(async (target, index) => {
            const evidence = await regulatoryIntelligenceService.retrieveAndGrade({
              question: target.text,
              feature: 'POLICY_CITATION_VERIFICATION',
              jurisdictionContext,
              organizationContext: { organizationId: ctx.orgMembership!.organizationId },
              retrievalProfile: {
                topK: 3,
                minScore: 0.7,
                filter: target.documentId ? { documentId: { $eq: target.documentId } } : undefined,
              },
            }).then((result) => result.evidence).catch(() => []);
            const exactIdentityRequired = !!target.vectorId || !!target.chunkId;
            const identityMatched = evidence.some((match) => (
              (!target.vectorId || match.vectorId === target.vectorId) &&
              (!target.chunkId || match.chunkId === target.chunkId) &&
              (!target.documentId || match.documentId === target.documentId)
            ));
            const verified = exactIdentityRequired ? identityMatched : evidence.length > 0;
            return {
              index: index + 1,
              citation: target.text,
              verified,
              sourceCount: evidence.length,
              expected: {
                vectorId: target.vectorId ?? null,
                chunkId: target.chunkId ?? null,
                documentId: target.documentId ?? null,
              },
              sources: evidence.map((match) => ({
                vectorId: match.vectorId,
                chunkId: match.chunkId,
                documentId: match.documentId,
                documentTitle: match.documentTitle,
                section: match.section ?? null,
                jurisdictionCode: match.jurisdictionCode ?? null,
                score: match.score,
              })),
            };
          }),
        );

        const verified = checks.filter((check) => check.verified).length;
        const verificationResults = {
          content: JSON.stringify({ checks }, null, 2),
          model: 'corpus-search',
          inputTokens: 0,
          outputTokens: 0,
          cost: 0,
          citationCount: checks.length,
          verified,
          failed: checks.length - verified,
        };

        logger.info({
          type: 'policy_citations_verified',
          userId: ctx.user!.id,
          policyId: input.id,
          totalCitations: policy.citations.length,
        });

        return verificationResults;
      } catch (error: any) {
        logger.error({
          type: 'policy_verify_citations_error',
          userId: ctx.user!.id,
          policyId: input.id,
          error: error.message,
        });

        if (error instanceof TRPCError) {
          throw error;
        }

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to verify citations',
          cause: error,
        });
      }
    }),

  /**
   * Get policy generation status (poll endpoint)
   *
   * Used by the frontend to poll status after calling `generate`.
   * Returns status + progress so the UI can show a progress bar.
   *
   * @protected
   */
  getStatus: orgMemberProcedure
    .input(z.object({ policyId: z.string().min(1) }))
    .query(async ({ input, ctx }) => {
      try {
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.policyId },
          select: {
            id: true,
            status: true,
            userId: true,
            organizationId: true,
            title: true,
            generationMetadata: true,
            deletedAt: true,
            createdAt: true,
            updatedAt: true,
          },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Access control
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;
          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        // Derive a numeric progress from the status
        const progressMap: Record<string, number> = {
          DRAFT: 0,
          GENERATING: 50,
          COMPLETED: 100,
          FAILED: 0,
          ARCHIVED: 100,
        };

        const meta = policy.generationMetadata as Record<string, any> | null;

        return {
          policyId: policy.id,
          title: policy.title,
          status: policy.status,
          progress: progressMap[policy.status] ?? 0,
          isComplete: policy.status === 'COMPLETED',
          isFailed: policy.status === 'FAILED',
          errorMessage: meta?.error ?? null,
          generatedAt: meta?.generatedAt ?? null,
          tokensUsed: meta?.tokensUsed ?? null,
          updatedAt: policy.updatedAt,
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_get_status_error',
          userId: ctx.user!.id,
          policyId: input.policyId,
          error: error.message,
        });

        if (error instanceof TRPCError) throw error;

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to get policy status',
          cause: error,
        });
      }
    }),

  /**
   * Get version history for a policy
   *
   * Returns the chain of versions linked via the parentId relation on Policy.
   *
   * @protected
   */
  getVersionHistory: orgMemberProcedure
    .input(z.object({ policyId: z.string().min(1) }))
    .query(async ({ input, ctx }) => {
      try {
        const policy = await ctx.prisma.policy.findUnique({
          where: { id: input.policyId },
          select: {
            id: true,
            userId: true,
            organizationId: true,
            parentId: true,
            deletedAt: true,
            version: true,
          },
        });

        if (!policy || policy.deletedAt) {
          throw new TRPCError({
            code: 'NOT_FOUND',
            message: 'Policy not found',
          });
        }

        // Access control
        if (ctx.user!.role !== 'ADMIN') {
          const hasAccess = policy.organizationId
            ? policy.organizationId === ctx.orgMembership!.organizationId
            : policy.userId === ctx.user!.id;
          if (!hasAccess) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'Access denied to this policy',
            });
          }
        }

        // Resolve root policy ID (walk up parentId chain if needed)
        const rootId = policy.parentId ?? policy.id;

        // Fetch all versions in the family
        const versions = await ctx.prisma.policy.findMany({
          where: {
            OR: [
              { id: rootId },
              { parentId: rootId },
            ],
            deletedAt: null,
          },
          orderBy: { version: 'asc' },
          select: {
            id: true,
            title: true,
            version: true,
            status: true,
            createdAt: true,
            updatedAt: true,
            isLatestVersion: true,
          },
        });

        return {
          policyId: input.policyId,
          rootId,
          versions,
        };
      } catch (error: any) {
        logger.error({
          type: 'policy_version_history_error',
          userId: ctx.user!.id,
          policyId: input.policyId,
          error: error.message,
        });

        if (error instanceof TRPCError) throw error;

        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to get policy version history',
          cause: error,
        });
      }
    }),
});
