import { logger } from '@/utils/logger';

/**
 * Embedding provider type
 * Using Pinecone integrated embeddings only.
 */
export type EmbeddingProvider = 'pinecone-integrated';

/**
 * Embedding configuration
 */
interface EmbeddingConfig {
  provider: EmbeddingProvider;
  model: string;
  dimension: number | null; // Managed by Pinecone
}

/**
 * Static config for integrated embedding mode
 */
const EMBEDDING_CONFIG: EmbeddingConfig = {
  provider: 'pinecone-integrated',
  model: 'multilingual-e5-large',
  dimension: 1024, // Informational only (Pinecone manages this)
};

/**
 * Get embedding configuration
 */
export function getEmbeddingConfig(): EmbeddingConfig {
  return EMBEDDING_CONFIG;
}

/**
 * IMPORTANT:
 * In integrated mode, embeddings are generated by Pinecone
 * during upsert. These functions should NEVER be called.
 */

export async function generateEmbedding(): Promise<never> {
  const error =
    'generateEmbedding() was called, but Pinecone integrated embeddings are enabled. Remove embedding generation from your ingestion pipeline.';
  
  logger.error({
    type: 'embedding_generation_called_in_integrated_mode',
  });

  throw new Error(error);
}

export async function generateBatchEmbeddings(): Promise<never> {
  const error =
    'generateBatchEmbeddings() was called, but Pinecone integrated embeddings are enabled. Remove batch embedding generation from your ingestion pipeline.';

  logger.error({
    type: 'batch_embedding_generation_called_in_integrated_mode',
  });

  throw new Error(error);
}

/**
 * Cosine similarity utility (useful for testing / diagnostics)
 */
export function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length) {
    throw new Error('Vectors must have same length');
  }

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < a.length; i++) {
    dotProduct += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }

  normA = Math.sqrt(normA);
  normB = Math.sqrt(normB);

  if (normA === 0 || normB === 0) {
    return 0;
  }

  return dotProduct / (normA * normB);
}

/**
 * Normalize vector (optional utility)
 */
export function normalizeVector(vector: number[]): number[] {
  const norm = Math.sqrt(vector.reduce((sum, val) => sum + val * val, 0));

  if (norm === 0) {
    return vector;
  }

  return vector.map((val) => val / norm);
}

/**
 * Embedding stats (static in integrated mode)
 */
export async function getEmbeddingStats(): Promise<{
  provider: EmbeddingProvider;
  model: string;
  dimension: number | null;
  cacheSize: number;
}> {
  return {
    provider: EMBEDDING_CONFIG.provider,
    model: EMBEDDING_CONFIG.model,
    dimension: EMBEDDING_CONFIG.dimension,
    cacheSize: 0, // No local cache used
  };
}

/**
 * Clear embedding cache (no-op in integrated mode)
 */
export async function clearEmbeddingCache(): Promise<number> {
  logger.warn({
    type: 'clear_embedding_cache_called_in_integrated_mode',
  });

  return 0;
}